config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  get 'auth/:provider/callback' => 'sessions#omniauth'
  get 'auth/failure', to: redirect('/')

  get '/signup' => 'sessions#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users, only: [:new, :create, :show]
  resources :comments 
  resources :games do 
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :game
    accepts_nested_attributes_for :user
    # def user_attributes=(user_attributes)
    #     self.user = User.find_or_create_by(username: user_attributes[:username]) unless user_attributes[:username].blank?
    # end
    # validates :body, presence: true

    def self.org
        self.order(:name)
    end
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :user
    belongs_to :genre 
    has_many :comments, dependent: :destroy 
    has_many :users, through: :comments 

    validates :name, :developer, :description, presence: true
    validates :release_year, numericality: {only_integer: true}


    def self.org
        self.order(:name)
    end

    def self.most_popular
        self.all.sort_by do |game|
            game.comments.length
        end.reverse 
    end
end

app/models/genre.rb
class Genre < ApplicationRecord 
    has_many :games 

    validates :name, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :games 
    has_many :received_comments, through: :games, source: :comments 
    has_many :comments, dependent: :destroy 
    has_many :commented_games, through: :comments, source: :game

    validates :username, :email, presence: true 
    validates :email, uniqueness: true 

    def self.from_omniauth(response)

        User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
            u.username = response[:info][:name]
            u.email = response[:info][:email]
            u.password = SecureRandom.hex(15)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include ApplicationHelper
    add_flash_types :info, :error, :warning
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_comment, only: [:show, :edit, :update, :destroy]
    before_action :redirect_if_not_user, only: [:edit, :update, :destroy]

    def index
    @game = Game.find_by(id: params[:game_id])
    @comments = Comment.org
        if params[:game_id]
            @comments = Game.find(params[:game_id]).comments
        else
            @comments = Comment.all
        end
    end

    def new 
        @game = Game.find(params[:game_id])
        @comment = @game.comments.build
    end

    def create 
        @game = Game.find(params[:game_id])
        @comment = @game.comments.build(comment_params)
        @comment.user_id = current_user.id 
        if @comment.save 
            redirect_to game_path(@game)
         else
            redirect_to new_game_comment_path(@game)
        end
    end

    def show 
        find_comment
    end

    def edit 
        find_comment
    end

    def update 
        find_comment
        if @comment.user == current_user 
            @comment.update(comment_params)
            redirect_to game_path(@comment.game_id)
        else
            render :edit 
        end
    end

    def destroy 
        find_comment 
        if @comment.user == current_user
            @comment.destroy 
            redirect_to games_path
        else
            redirect_to games_path
        end
    end 

    private 

    def comment_params 
        params.require(:comment).permit(:body, :game_id, user_attributes: [:username])
    end

    def redirect_if_not_user 
        if @comment.user != current_user 
            redirect_to user_path(current_user), alert: "You Do Not Have Permission To Edit This Comment!"
        end
    end

    def find_comment 
        @comment = Comment.find(params[:id])
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :find_game, only: [:show, :edit, :update, :destroy]
    before_action :redirect_if_not_user, only: [:edit, :update, :destroy]

    def index
        @games = Game.most_popular
    end

    def new 
        @game = Game.new
    end

    def create 
        @game = current_user.games.build(game_params)
        @genres = Genre.all
        if @game.valid?
            @game.save
            redirect_to game_path(@game)
        else 
            @game = Game.find_by_id(params[:game_id]) if params[:game_id]
            render :new 
        end
    end

    def edit 
        find_game
    end

    def update 
        find_game
        if @game.user == current_user 
            @game.update(game_params)
            redirect_to game_path(@game)
        else
            render :edit 
        end
    end

    def show 

    end

    def destroy 
        @game.destroy 
        redirect_to games_path
    end


    private 

    def game_params 
        params.require(:game).permit(:name, :developer, :release_year, :description, :genre_id, :genre, :id, :uid)
    end

    def redirect_if_not_user 
        if @game.user != current_user 
            redirect_to user_path(current_user), alert: "You Do Not Have Permission To Edit This Game!"
        end
    end

    def find_game 
        @game = Game.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 

    end

    def create 
        user = User.find_by_email(params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id 
            redirect_to user_path(user)
        else
            redirect_to '/login', alert: "Invalid credentials. Please try again."
        end
    end

    def destroy 
        session.delete(:user_id)
        redirect_to '/login'
    end

    def omniauth
        user = User.from_omniauth(request.env['omniauth.auth'])
            if user.valid?
            session[:user_id] = user.id 
            redirect_to user_path(user)
            else
                redirect_to '/login'
            end
    
    end

    private 

    def auth 
        request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new 
        @user = User.new 
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else
            render :new 
        end
    end

    def show 
        @user = User.find_by_id(params[:id])
    end

    private 
    def user_params 
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user 
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for [@comment.game, @comment] do |f| %>
    <%= f.label :review %>
    <%= f.text_field :body %>
    <br>
    <%= f.submit "Leave Comment"%>
<% end %>

app/views/comments/edit.html.erb
<h1> Edit Your Comment </h1>
<%= render 'form' %>

app/views/comments/index.html.erb
<h1> <b>Comments</b> on <b><%= @game.name %></b></h1>
<% @comments.each do |comment| %>
    "<%= comment.body %>" on <%= comment.game.name %>.<br>
    <br><%= link_to 'Edit', edit_game_comment_path(@game, comment) %>
    <%= link_to "Delete", comment, method: :delete, data: {:confirm => 'Delete this comment?'} %><br><br>
<% end %>

app/views/comments/new.html.erb
<h1> Add A New Review </h1>
<%= render partial: 'form', locals: { game: @game, comment: @comment } %>

app/views/comments/show.html.erb
<h1> Add A Comment </h1>
<b> <%= @comments.game.user.username %> wrote: </b>

app/views/games/_form.html.erb
<%=form_for(@game) do |f|%>
    <% if @game.errors.any? %>
    <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        <% end %>
    <div class="form-group">
        <%= f.label :Name %><br>
        <%= f.text_field :name, class: "form-control" %></div>
    <div class="form-group">
        <%= f.label :Developer %><br>
        <%= f.text_field :developer, class: "form-control" %></div>
    <div class="form-group">
        <%= f.label :Release_Year %><br>
        <%= f.number_field :release_year, class: "form-control" %></div>
    <div class="form-group">
        <%= f.label :Genre%><br>
        <%= f.collection_select :genre_id, Genre.all, :id, :name, class: "form-control" %></div>
    <div class="form-group">
        <%= f.label :Description %><br>
        <%= f.text_area :description, class: "form-control" %></div>
    <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
        </div>
<% end %>

app/views/games/edit.html.erb
<h1> Edit Your Game </h2>
<%= render 'form' %>

app/views/games/index.html.erb
<h1> Index </h1>
<% @games.each do |game|%>
    <div> 
    <%= link_to game.name, game_path(game.id) %>
    </div>
<%end%>

app/views/games/new.html.erb
<h1> Create a Game </h1>
<%= render 'form' %>

app/views/games/show.html.erb
<h1><b><%= @game.name %></b> <small>- added by: <%= @game.user.username %> </small></h1>

<h2><%= @game.release_year %></h2>

<b>Genre: </b> <%= @game.genre.name %><br><br>

<b>Developer: </b> <%= @game.developer %><br><br>

<b>Info: </b> <%= @game.description %><br><br>

<%= link_to 'Edit Game', [:edit, @game] %>

<%= link_to 'Delete Game', @game, method: :delete, data: { confirm: 'Are you sure?' } %><br>

<%= link_to "Add A Review", new_game_comment_path(@game) %><br>
<%= link_to 'View All Reviews', game_comments_path(@game) %><br><br>

<b>Comments: </b><br>
<% @game.comments.each do |comment| %>
    "<%= comment.body %>" -by: <b><%= comment.user.username %></b><br>
    <%= link_to 'Edit Comment', edit_game_comment_path(@game, comment) %>
    <%= link_to 'Delete Comment', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br><br>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamesFull</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/bulmaswatch/nuclear/bulmaswatch.min.css">
    <div class="wrapper" role="navigation">
  </head>

  <body>
  <div class="wrapper" role="navigation" aria-lebel="main navigation">
      <div class="container">
        <% if !current_user %>
          <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
          <a class="navbar-brand" href="<%= new_user_path %>"/>Sign Up</a>
          <%= link_to "Sign in", login_path, class:"navbar-brand" %>
          <% else %>
          <a class="navbar-brand" href="<%= games_path %>"/>Home</a>
          <%= link_to "#{current_user.username}'s Profile", user_path(current_user), class:"navbar-brand"%>
          <%= link_to "Sign Out", logout_path, class:"navbar-brand", method:'delete' %>
        <% end %>

        <% flash.each do |name, message| -%>
          <%= content_tag :div, message, class: "notification is-warning" %>
        <% end %>
        
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this from being saved:</h2>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

    <div class = "user-form">
        <%= f.label :Name %>:
        <%= f.text_field :username %><br>
        <%= f.label :email %>:
        <%= f.text_field :email %><br>
        <%= f.label :password %>:
        <%= f.password_field :password %><br>
        <%= f.label :password_confirmation %>:
        <%= f.password_field :password_confirmation %><br><br>
    </div>
    <div class = "submit-button">
        <%= f.submit "Create User"%>
    </div>
<% end %>

app/views/users/new.html.erb
<h1> Sign Up</h1>
<%= render partial: '/shared/errors', locals: {obj: @user }%>
<%= render 'form' %>

app/views/users/show.html.erb
<h1> Your Games and Reviews</h1>
<h2>Games</h2>
<% @user.games.org.each do |game|%>
    <div>
    <%= link_to game.name, game_path(game.id) %>
    </div>
<%end%>
<p><%= link_to "Create A Game", new_game_path %></p>
<h2>Comments</h2>
<% @user.comments.each do |comment, game| %>
    "<%= comment.body %>" on <%= comment.game.name %>.<br>
<% end %>

app/views/welcome/home.html.erb
<h1> Welcome to the Game Forum! </h1>
<p> Please sign up or sign in:</p>
<%= link_to "Sign Up", new_user_path %>
<%= link_to "Log In", login_path %>